### ISSUE TITLE
On improving the usability

### ISSUE THREAD

**Issue by aPonza** [ethz-asl/eclipsify#39]
There are some things that are not automatized by eclipsify yet, and some that could be useful to have written in the README for it to automatize the use of eclipsify further. In particular:
- the [Preliminary Setup](https://github.com/ethz-asl/programming_guidelines/wiki/Catkin-Eclipse#preliminary-setup-global-settings-in-eclipse) has to still be done manually, and this could be added to the readme;
- the [general guide for adding a package without eclipsify](https://github.com/ethz-asl/programming_guidelines/wiki/Catkin-Eclipse#adding-a-catkin-package-as-project-to-eclipse) states at some point: "Go to "C/C++ General"->"Preprocessor Includes", "Providers" tab. Check "CDT GCC Build Output Parser" and "CDT GCC Built-in Compiler Settings" and verify that you "Use global provider shared between projects" in both. "Apply" and "OK"." This has to be still done manually for the includes to resolve, for every package, after the import in eclipse, and I'm wondering if the flags could instead be toggled internally.

**Comment by HannesSommer** [comment]
Thanks @aPonza for your hints.
I agree partially with your first bullet point regarding the "CDT GCC Built-in Compiler Settings" even though it is not really eclipsify's concern how the workspace is setup. For instance it is not clear that eclipsify is always combined with c++11. Nevertheless it is probably a good idea to add your reference to the README regarding workspace setup.

However, your second suggestion and equally the corresponding part of  [Preliminary Setup](https://github.com/ethz-asl/programming_guidelines/wiki/Catkin-Eclipse#preliminary-setup-global-settings-in-eclipse) should not be necessary with the current templates. They do not use the global Build Output Parser but rely on project wise parser configuration.
Maybe they didn't work for you for some other reason? They work fine for others. I've just tested with a fresh workspace.
What gave you the impression that eclipsify is doing exactly what [general guide for adding a package without eclipsify](https://github.com/ethz-asl/programming_guidelines/wiki/Catkin-Eclipse#adding-a-catkin-package-as-project-to-eclipse) suggests? Is that written somewhere?

The choice between project specific or shared include providers is a matter of taste. Thanks to its flexible template system eclipsify can be used with both. Merely the default templates go for per project output parsers and shared build-in compiler parser.

**Comment by aPonza** [comment]
Mmm no, in my second point I'm not suggesting eclipsify is doing what the guide suggests, in fact, I'm saying I have to do those steps manually for the includes to resolve (and I understand I could setup all my packages manually to work like that instead of using the shared settings, but at the moment I'm only working with C++14 so it wouldn't make sense for me). You are right that it relates mostly to me using C++14 (same would be for C++11). It's likely I was referring to the specifics of usage with modern C++ without realizing that's not the typical user.

**Comment by HannesSommer** [comment]
I think there is a misunderstanding. By current eclipsify design it should not be necessary to change anything in the global workspace to the project for the include paths to be found properly by eclipse. 

The only exception is if you use a different language standard for the workspace than what the project needs. But that mismatch does only affect a small part of the code analysis, because the differences are not that big. So, in this case it should work mostly. 

To understand that you have to distinguish the language standard dependent macros and includes from the project specific includes. 
When using eclipsify with its current templates, the language standard you choose (c+11, ..) globally for the workspace (as described in the guideline) directly effects all the projects created with eclipsify, because eclipsify's templates use the shared providers here.

For the project specific includes it is different. Here the results of the output parser are not shared between projects! And hence the project specific includes should work independently of workspace or other project's settings / indexer state.

For debuging include discovery I strongly recommend not to look at the indexer behaviour but much rather the output lists in the project's setting for the providers or -- much easier  -- the `includes` folder in the `C++ Projects Explorer` view. It contains a live list of the found includes per project.
